export default options = { 
    column1: [
        { label: '0' },
        { label: '1' },
        { label: '2' },
        { label: '3' },
        { label: '4' },
        { label: '5' },
        { label: '6' },
        { label: '7' },
        { label: '8' },
        { label: '9' },
        { label: '10' },
        { label: '11' },
        { label: '12' },
        { label: '13' },
        { label: '14' },
        { label: '15' },
        { label: '16' },
        { label: '17' },
        { label: '18' },
        { label: '19' },
        { label: '20' },
        { label: '21' },
        { label: '22' },
        { label: '23' },
        { label: '24' },
        { label: '25' },
        { label: '26' },
        { label: '27' },
        { label: '28' },
        { label: '29' },
        { label: '30' },
        { label: '31' },
        { label: '32' },
        { label: '33' },
        { label: '34' },
        { label: '35' },
        { label: '36' },
        { label: '37' },
        { label: '38' },
        { label: '39' },
        { label: '40' },
        { label: '41' },
        { label: '42' },
        { label: '43' },
        { label: '44' },
        { label: '45' },
        { label: '46' },
        { label: '47' },
        { label: '48' },
        { label: '49' },
        { label: '50' },
    ],
    column2: [
        { label: ' ' },
        { label: '1/8' },
        { label: '1/4' },
        { label: '1/3' },
        { label: '1/2' },
        { label: '2/3' },
        { label: '3/4' },
    ],
    column3: [
        { label: ' ' },
        { label: 'OZ' },
        { label: 'ML' },
        { label: 'CL' },
        { label: 'L' },
        { label: 'CUP' },
        { label: 'PINT' },
        { label: 'TSP' },
        { label: 'TBSP' },
        { label: 'DASH' },
        { label: 'DROP' },
        { label: 'PINCH' },
    ]
}